#!/bin/bash
##
## mkkaliusb
## ---------
## Create a Kali or Ubuntu Linux USB flash drive that is bootable both from
## BIOS and EFI.
##
## Usage:
##
##         mkkaliusb [ISO] [device] <optional FS label>
##

if [ "$1" == "" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
  grep -E '^##[^#]?' "$0" | sed -E 's/## ?//g'
  if [ "$1" == "" ] ; then
    echo
    echo "Available devices:"
    fdisk -l | grep -E '/dev/sd[a-z][^0-9]'
    echo
  fi
  exit
fi

ISO=$1
DEVICE=$2
LABEL=$3

if [ "$LABEL" == "" ]; then
    LABEL=Kali
fi

# Check whether format-usb is in the current directory or available in the
# path.
if  ! ( [ -e "./format-usb" ] || which format-usb ) ; then
    echo "Cannot find format-usb in the current directory or the default path."
    exit
fi
FORMATUSB=$(which format-usb || echo ./format-usb)

if ! ( which grub-install || which fatattr ) ; then
    cat <<EOF
One or more dependencies are missing.
Please make sure the following packages are installed:
    grub-pc
    fatattr
EOF
exit
fi

# Check that the ISO is valid
#if [ "$(file \"$ISO\" | grep -iEo 'bootable')" == "" ] ; then
#    echo "The ISO you are using does not appear to be a bootable Windows ISO."
#    exit
#fi

# Format the flash drive
$FORMATUSB $DEVICE "$LABEL"

TMPDIR=/tmp/$(basename "$0")
umount -f $TMPDIR/iso
umount -f $TMPDIR/usb
#rm -rfv $TMPDIR
mkdir $TMPDIR

# Mount the ISO
mkdir -p $TMPDIR/iso
mount "$ISO" $TMPDIR/iso -o loop,ro

# Mount the USB
mkdir -p $TMPDIR/usb
mount -t vfat $DEVICE"1" $TMPDIR/usb -o rw

#echo Flash drive formatted and mounted.
#echo Install grub and grub.cfg now
#read -p "Press ENTER to continue"

#grub-install --boot-directory=$TMPDIR/usb/boot --efi-directory=$TMPDIR/usb --force --removable --uefi-secure-boot $DEVICE
# Install grub for non-EFI systems
grub-install --boot-directory=$TMPDIR/usb/boot --target=i386-pc --force --removable $DEVICE
cp $TMPDIR/iso/boot/grub/loopback.cfg $TMPDIR/usb/boot/grub/grub.cfg
#sed -iE 's/Debian/Kali/g' $TMPDIR/usb/boot/grub/grub.cfg
# Create files for EFI boot
cp -Rv EFI $TMPDIR/usb/
#cp $TMPDIR/iso/boot/grub/loopback.cfg $TMPDIR/usb/EFI/Boot/grub.cfg

# Copy all files from the ISO to the USB
cp -RvL $TMPDIR/iso/* $TMPDIR/usb

# Fix Ubuntu boot options to detect flash drive
sed -i -E 's#file=/cdrom/preseed/.+\.seed#live-media-path=/casper/ ignore_uuid#g' "$TMPDIR/usb/boot/grub/grub.cfg"
sed -i -E 's#file=/cdrom/preseed/.+\.seed#live-media-path=/casper/ ignore_uuid#g' "$TMPDIR/usb/EFI/Boot/grub.cfg"

# Apply the flash drive label using autorun.inf
cat <<EOF > "$TMPDIR/usb/autorun.inf"
[autorun]
;open=explorer.exe
;icon=icon.ico,0
label=$LABEL

[Content]
MusicFiles=True
PictureFiles=True
VideoFiles=True
EOF

# Hide all files on the flash drive from Windows
fatattr +r +h +s $TMPDIR/usb/*

# Unmount the ISO and USB
umount $TMPDIR/iso
umount $TMPDIR/usb

echo 'DONE! Eject flash drive with "eject '$DEVICE'".'
#eject $DEVICE && echo "$DEVICE Ejected"'!' && echo "Please remove the flash drive now."
